name: Scorecard supply-chain security
on:
  branch_protection_rule:
  workflow_dispatch:
  schedule:
    - cron: "20 7 * * 2"
  push:
    branches: ["main"]

permissions: read-all

jobs:
  analysis:
    if: github.repository == 'oaslananka-lab/fovux' && github.ref == 'refs/heads/main'
    name: Scorecard analysis
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: read
      id-token: write

    steps:
      - name: "Checkout code"
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          persist-credentials: false

      - name: "Run analysis"
        uses: ossf/scorecard-action@4eaacf0543bb3f2c246792bd56e8cdeffafb205a
        with:
          results_file: results.json
          results_format: json
          publish_results: true

      - name: "Upload artifact"
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
          name: scorecard-results
          path: results.json
          retention-days: 5
